### ISSUE TITLE
generate qcow2 images

### ISSUE THREAD

**Issue by shibumi** [archlinux/arch-boxes#30]
We want to provide qcow2 images for cloud providers like openstack or hetzner cloud. Therefore we need to have a new json specification for packer. This way we keep our vagrant build specification clean.

Things what need to be done:
* moving `cloud-init` back to official repositories
* write a new specification for cloud images with provision scripts
* modifying the ansible role in the infrastructure repository

**Comment by shibumi** [comment]
Update:

* finished moving cloud-init + netplan to community
* new json for cloud images is needed + provision scripts for installing cloud-init

* Ansible role is not needed, I am going to build the cloud images locally and sign them with my key.

**Comment by shibumi** [comment]
Update:

* new json cloud image + provision scripts finished

To do:

* Directory on pkgbuild.com
* Automating
* Further testing
* Waiting for cloud-init 19.3

**Comment by evaryont** [comment]
I was just looking for this, specifically to play around with VMs managed by `machinectl`. Exciting!

> Waiting for cloud-init 19.3

@shibumi out of curiosity, what is going to be included in the next version that you are waiting for?

**Comment by shibumi** [comment]
@evaryont cloud-init 19.3 will come with native Arch Linux supports, so we can drop the archlinux.cfg in our community package and just use the generated one (which will have more features).

**Comment by FFY00** [comment]
@shibumi any update?

**Comment by shibumi** [comment]
@FFY00 Yep, I have some trouble with cloud-init. It's either not working properly on Arch Linux or I am just using it wrong. Didn't had time yet to dive more into it. If you want to check it out have a look on the repo, there should be a cloud.yml file for vagrant.

**Comment by FFY00** [comment]
I tried provisioning your cloudimage build from https://pkgbuild.com with terraform to my libvirt server but it doesn't seem to apply `cloud_init.cfg` settings. Is this the kind of issues you were facing or am I just not passing the config properly? During boot I managed to see some errors but I don't have time to dive in right now.

**Comment by shibumi** [comment]
@FFY00 yep, this is the problem I were facing and I have no idea yet how to fix it.

**Comment by FFY00** [comment]
The error being thrown is at https://github.com/canonical/cloud-init/blob/13e82554728b1cb524438163784e5b955c7c5ed0/cloudinit/net/netplan.py#L256. `udevadm test-builtin net_setup_link /sys/class/net/lo` fails with `No such file or directory`.

**Comment by shibumi** [comment]
No idea, I will ask a cloud-init contributor. Maybe he has an idea about what is going on.

**Comment by FFY00** [comment]
It seems to be related to systemd, `/sys/class/net/lo` should exist because cloud-init is looping over the existing interfaces.

**Comment by klausenbusk** [comment]
> It seems to be related to systemd, `/sys/class/net/lo` should exist because cloud-init is looping over the existing interfaces.

`rm /etc/systemd/network/99-default.link` seems to fix the issue. It is added here: https://github.com/archlinux/arch-boxes/blob/b52f4d3efd7802b31763d84d520f980eb078ceaf/http/install-cloud.sh#L33, can we remove the line?

**Comment by FFY00** [comment]
But we are just symlinking `/dev/null`? It shouldn't affect anything, I think. @shibumi could you clarify?

**Comment by FFY00** [comment]
From https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

> Starting with v197 systemd/udev will automatically assign predictable, stable network interface names for all local Ethernet, WLAN and WWAN interfaces. This is a departure from the traditional interface naming scheme ("eth0", "eth1", "wlan0", ...), but should fix real problems.

**Comment by klausenbusk** [comment]
> But we are just symlinking `/dev/null`? It shouldn't affect anything, I think. @shibumi could you clarify?

By overriding `99-default.link` a default link configuration isn't created which cause `net_setup_link` to [fail](https://github.com/systemd/systemd/blob/a63932778cafdf6cb2d6542d3ffa21b518abc148/src/udev/udev-builtin-net_setup_link.c#L28).
```sh
[vagrant@archlinux network]$ sudo udevadm -d test-builtin net_setup_link /sys/class/net/lo
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
Trying to open "/usr/lib/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          244
file size:         9826248 bytes
header size             80 bytes
strings            2137056 bytes
nodes              7689112 bytes
Load module index
Found container virtualization none.
timestamp of '/etc/systemd/network' changed
Skipping overridden file '/usr/lib/systemd/network/99-default.link'.
Skipping empty file: /etc/systemd/network/99-default.link
Parsed configuration file /run/systemd/network/10-netplan-eth0.link
Created link configuration context.
lo: No matching link configuration found.
Builtin command 'net_setup_link' fails: No such file or directory
Unload module index
Unloaded link configuration context.
[vagrant@archlinux network]$ sudo rm 99-default.link 
[vagrant@archlinux network]$ sudo udevadm -d test-builtin net_setup_link /sys/class/net/lo
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
Trying to open "/usr/lib/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          244
file size:         9826248 bytes
header size             80 bytes
strings            2137056 bytes
nodes              7689112 bytes
Load module index
Found container virtualization none.
timestamp of '/etc/systemd/network' changed
Parsed configuration file /usr/lib/systemd/network/99-default.link
Parsed configuration file /run/systemd/network/10-netplan-eth0.link
Created link configuration context.
lo: Config file /usr/lib/systemd/network/99-default.link is applied
ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
lo: Failed to query name_assign_type: Invalid argument
lo: Policies didn't yield a name and Name= is not given, not renaming.
lo: Device has addr_assign_type=0
lo: MAC on the device already matches policy *persistent*
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
Unload module index
Unloaded link configuration context.
[vagrant@archlinux ~]$ networkctl status -a
● 1: lo                                                 
             Link File: n/a                             
          Network File: n/a                             
                  Type: loopback                        
                 State: carrier (unmanaged)
                   MTU: 65536                           
  Queue Length (Tx/Rx): 1/1                             
               Address: 127.0.0.1                       
                        ::1                             

● 2: eth0                                                                     
             Link File: /run/systemd/network/10-netplan-eth0.link             
          Network File: /run/systemd/network/10-netplan-eth0.network          
                  Type: ether                                                 
                 State: routable (configuring)
                  Path: pci-0000:00:05.0                                      
                Driver: virtio_net                                            
                Vendor: Red Hat, Inc.                                         
                 Model: Virtio network device                                 
            HW Address: 52:54:00:87:19:52                                     
                   MTU: 1500 (min: 68, max: 65535)                            
  Queue Length (Tx/Rx): 1/1                                                   
      Auto negotiation: no                                                    
                 Speed: n/a                                                   
               Address: 192.168.121.177 (DHCP4)                               
                        fe80::5054:ff:fe87:1952                               
               Gateway: 192.168.121.1                                         
                   DNS: 192.168.121.1 
```

> From https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
> 
> > Starting with v197 systemd/udev will automatically assign predictable, stable network interface names for all local Ethernet, WLAN and WWAN interfaces. This is a departure from the traditional interface naming scheme ("eth0", "eth1", "wlan0", ...), but should fix real problems.

The easiest solution is probably appending `net.ifnames=0` to `GRUB_CMDLINE_LINUX=` in `/etc/default/grub`. I'm not sure it is the best solution though.

**Comment by shibumi** [comment]
Mhhh, actually we wanted to have the traditional interface naming scheme, because it's easier in VM environments. A VM will always come up with `eth0` this way. If we enable predicted names, we will end up with different interface names in different VM environments. See also:

https://github.com/archlinux/arch-boxes/blob/master/http/install-chroot.sh#L41L48

If we change to predictable names, we will need a new way for setting up the network.
We could use wildcards like `e*`, but I am afraid this could break more complex setups.

What do you think?

**Comment by FFY00** [comment]
I think this is solvable by changing https://github.com/delphix/cloud-init/blob/cde58a45d7cf45b546039e6ffc6fc88a5d0077ef/cloudinit/distros/arch.py#L32 to `False` but I don't have time to try right now. Also, packer decided it didn't want to build the image anymore.

**Comment by FFY00** [comment]
Well, that will disable netplan so probably not.

**Comment by klausenbusk** [comment]
I just had a quick look at how Debian does it. [They](https://salsa.debian.org/openstack-team/debian/openstack-debian-images/blob/fb1d5be0b84895c96f8209f6e7177cf1f6bf1b25/build-openstack-debian-image#L1861) add `net.ifnames=0` to the kernel command line, which disable `Predictable Network Interface Names` as documented in [systemd.link(5)](https://www.freedesktop.org/software/systemd/man/systemd.link.html#NamePolicy=).

So I propose the following patch (not tested):
```diff
diff --git a/http/install-chroot.sh b/http/install-chroot.sh
index 603ffdc..92bde92 100644
--- a/http/install-chroot.sh
+++ b/http/install-chroot.sh
@@ -35,9 +35,6 @@ curl --output /home/vagrant/.ssh/authorized_keys --location https://raw.github.c
 chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
 chmod 0600 /home/vagrant/.ssh/authorized_keys
 
-# setup unpredictable kernel names
-ln -s /dev/null /etc/systemd/network/99-default.link
-
 # setup network
 cat <<EOF >/etc/systemd/network/eth0.network
 [Match]
@@ -98,4 +95,6 @@ elif [ -b "/dev/vda" ]; then
   grub-install /dev/vda
 fi
 sed -i -e 's/^GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=1/' /etc/default/grub
+# setup unpredictable kernel names
+sed -i -e 's/^GRUB_CMDLINE_LINUX=.*$/GRUB_CMDLINE_LINUX="net.ifnames=0"/' /etc/default/grub
 grub-mkconfig -o /boot/grub/grub.cfg
diff --git a/http/install-cloud.sh b/http/install-cloud.sh
index 86d0508..84dec48 100644
--- a/http/install-cloud.sh
+++ b/http/install-cloud.sh
@@ -29,9 +29,6 @@ arch ALL=(ALL) NOPASSWD: ALL
 EOF
 chmod 440 /etc/sudoers.d/arch
 
-# setup unpredictable kernel names
-ln -s /dev/null /etc/systemd/network/99-default.link
-
 # setup network
 cat <<EOF >/etc/systemd/network/eth0.network
 [Match]
@@ -74,4 +71,6 @@ elif [ -b "/dev/vda" ]; then
   grub-install /dev/vda
 fi
 sed -i -e 's/^GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=1/' /etc/default/grub
+# setup unpredictable kernel names
+sed -i -e 's/^GRUB_CMDLINE_LINUX=.*$/GRUB_CMDLINE_LINUX="net.ifnames=0"/' /etc/default/grub
 grub-mkconfig -o /boot/grub/grub.cfg
```

BTW: I did notice that `install-chroot.sh` contain a `reflector-init.service`, which `install-cloud.sh` doesn't. Shouldn't they both contain that service? and is it possiable to move some of the common code to its own file, so we don't have two scripts with nearly identical code?

**Comment by shibumi** [comment]
@klausenbusk are you willing to make a PR out of it? (this includes the  part about sharing common code in one file).

**Comment by klausenbusk** [comment]
> @klausenbusk are you willing to make a PR out of it? (this includes the part about sharing common code in one file).

Sure, I will do that later.

**Comment by shibumi** [comment]
@klausenbusk cool can't wait to have a look on it.

**Comment by klausenbusk** [comment]
> @klausenbusk cool can't wait to have a look on it.

Done: https://github.com/archlinux/arch-boxes/pull/86. I don't have time to test it right now, but I think it works.

**Comment by shibumi** [comment]
@klausenbusk don't worry. I will do proper testing, before merging.

**Comment by FFY00** [comment]
The error seems to be gone but I still but my config still doesn't work. @klausenbusk have you had any luck booting with a custom config?

**Comment by klausenbusk** [comment]
> The error seems to be gone but I still but my config still doesn't work. @klausenbusk have you had any luck booting with a custom config?

I haven't tested yet. Could you share the config?

**Comment by FFY00** [comment]
I've tried a lot of different things, you could try:

```yaml
#cloud-init
users:
  - name: root
chpasswd:
  list: |
    root:password
  expire: False
```

**Comment by FFY00** [comment]
Nevermind, at config was missing the required `#cloud-init`. I deployed again and it worked. Sorry for bothering.

**Comment by shibumi** [comment]
@FFY00 did you test against the newest PR?

**Comment by FFY00** [comment]
I made the change locally and the error doesn't really seem to be gone, I only noticed this when I re-deployed the machine.

**Comment by shibumi** [comment]
Do you get a different error?

**Comment by FFY00** [comment]
No, it's the same.

**Comment by shibumi** [comment]
I will checkout the PR, build a new image and will test it (today or tomorrow).

**Comment by klausenbusk** [comment]
I just got time to test and fix the PR, it should work now.

I tested it with qemu and the [NoCloud](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) data source and it seems to work.
```
$ packer build cloud.json
$ cp release/Arch-Linux-cloudimg-amd64-2020-02-24.img disk.img

# Copied from (with minor changes): https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
$ { echo instance-id: iid-local01; echo local-hostname: cloudimg; } > meta-data

$ printf "#cloud-config\npassword: passw0rd\nchpasswd: { expire: False }\nssh_pwauth: True\n" > user-data

## create a disk to attach with some user-data and meta-data (require cdrkit)
$ genisoimage  -output seed.iso -volid cidata -joliet -rock user-data meta-data

## create a new qcow image to boot, backed by your original image
$ qemu-img create -f qcow2 -b disk.img boot-disk.img

## boot the image and login as 'arch' with password 'passw0rd'
## note, passw0rd was set as password through the user-data above,
## there is no password set on these images.
$ qemu-system-x86_64 -m 256 \
   -net nic -net user,hostfwd=tcp::2222-:22 \
   -drive file=boot-disk.img,if=virtio \
   -drive file=seed.iso,if=virtio
```

**Comment by shibumi** [comment]
Cool, let me follow your post and validate this. The image is building right now.

**Comment by shibumi** [comment]
Mh @klausenbusk I tried your guide and this is what I get: `qemu-system-x86_64: -drive file=seed.iso,if=virtioqemu-system-x86_64: unsupported bus type 'virtioqemu-system-x86_64'` am I missing a package?

**Comment by klausenbusk** [comment]
> Mh @klausenbusk I tried your guide and this is what I get: `qemu-system-x86_64: -drive file=seed.iso,if=virtioqemu-system-x86_64: unsupported bus type 'virtioqemu-system-x86_64'` am I missing a package?

Did you accidentally paste the command twice?

**Comment by shibumi** [comment]
@klausenbusk yes, thanks. Now it works. Let me merge this PR :)

**Comment by shibumi** [comment]
Fixed with #86
